server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root12
    url: jdbc:mysql://localhost:3306/insurance_eligibility_detalis?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: false
